import type { AccountTemplate } from "./types";

/** Moroccan Plan Comptable General des Entreprises (PCGE / CGNC) */
export const MA_ACCOUNTS: AccountTemplate[] = [
  // Class 1: Financement Permanent (Equity & Long-term Financing)
  { code: "1111", name: "Share Capital (Capital Social)", type: "equity", subType: "equity" },
  { code: "1140", name: "Legal Reserve", type: "equity", subType: "equity" },
  { code: "1151", name: "Other Reserves", type: "equity", subType: "equity" },
  { code: "1160", name: "Retained Earnings (Report a Nouveau)", type: "equity", subType: "retained" },
  { code: "1181", name: "Net Income for the Year (Profit)", type: "equity", subType: "equity" },
  { code: "1191", name: "Net Loss for the Year", type: "equity", subType: "equity" },
  { code: "1481", name: "Loans from Credit Institutions", type: "liability", subType: "non_current" },
  { code: "1487", name: "Other Financial Debts", type: "liability", subType: "non_current" },
  // Class 2: Immobilisations (Fixed Assets)
  { code: "2111", name: "Formation Costs (Frais de Constitution)", type: "asset", subType: "fixed" },
  { code: "2130", name: "Goodwill (Fonds Commercial)", type: "asset", subType: "fixed" },
  { code: "2220", name: "Land", type: "asset", subType: "fixed" },
  { code: "2230", name: "Buildings", type: "asset", subType: "fixed" },
  { code: "2340", name: "Vehicles (Materiel de Transport)", type: "asset", subType: "fixed" },
  { code: "2351", name: "Office Furniture", type: "asset", subType: "fixed" },
  { code: "2355", name: "Computer Equipment", type: "asset", subType: "fixed" },
  { code: "2810", name: "Accum. Amortisation - Intangible Assets", type: "asset", subType: "fixed" },
  { code: "2832", name: "Accum. Depreciation - Buildings", type: "asset", subType: "fixed" },
  { code: "2834", name: "Accum. Depreciation - Transport Equipment", type: "asset", subType: "fixed" },
  // Class 3: Actif Circulant (Inventory & Receivables)
  { code: "3111", name: "Goods for Resale (Marchandises)", type: "asset", subType: "current" },
  { code: "3121", name: "Raw Materials", type: "asset", subType: "current" },
  { code: "3151", name: "Finished Goods", type: "asset", subType: "current" },
  { code: "3421", name: "Trade Receivables (Clients)", type: "asset", subType: "current" },
  { code: "3427", name: "Doubtful Receivables", type: "asset", subType: "current" },
  { code: "3455", name: "Recoverable VAT (TVA Deductible)", type: "asset", subType: "current" },
  { code: "3493", name: "Prepaid Expenses", type: "asset", subType: "current" },
  // Class 4: Passif Circulant (Payables)
  { code: "4411", name: "Trade Payables (Fournisseurs)", type: "liability", subType: "current" },
  { code: "4415", name: "Suppliers - Invoices Not Yet Received", type: "liability", subType: "current" },
  { code: "4432", name: "Amounts Due to Personnel", type: "liability", subType: "current" },
  { code: "4441", name: "Corporate Income Tax Payable (IS)", type: "liability", subType: "current" },
  { code: "4452", name: "Employee Income Tax Withheld (IR)", type: "liability", subType: "current" },
  { code: "4455", name: "VAT Payable (TVA Facturee)", type: "liability", subType: "current" },
  { code: "4457", name: "State - Other Taxes Payable", type: "liability", subType: "current" },
  { code: "4462", name: "CNSS Payable", type: "liability", subType: "current" },
  // Class 5: Tresorerie (Cash & Bank)
  { code: "5141", name: "Bank Accounts", type: "asset", subType: "current" },
  { code: "5161", name: "Cash on Hand (Caisse)", type: "asset", subType: "current" },
  { code: "5520", name: "Short-term Bank Credit", type: "liability", subType: "current" },
  // Class 6: Charges (Expenses)
  { code: "6111", name: "Purchases of Goods for Resale", type: "expense", subType: "cogs" },
  { code: "6121", name: "Purchases of Raw Materials", type: "expense", subType: "cogs" },
  { code: "6131", name: "Rent (Locations)", type: "expense", subType: "operating" },
  { code: "6134", name: "Maintenance and Repairs", type: "expense", subType: "operating" },
  { code: "6142", name: "Transport of Goods", type: "expense", subType: "operating" },
  { code: "6144", name: "Advertising and Publications", type: "expense", subType: "operating" },
  { code: "6145", name: "Travel and Representation", type: "expense", subType: "operating" },
  { code: "6147", name: "Postage and Telecommunications", type: "expense", subType: "operating" },
  { code: "6148", name: "Banking Services", type: "expense", subType: "operating" },
  { code: "6160", name: "Insurance Premiums", type: "expense", subType: "operating" },
  { code: "6167", name: "Taxes and Duties (excl. Income Tax)", type: "expense", subType: "operating" },
  { code: "6171", name: "Salaries and Wages", type: "expense", subType: "operating" },
  { code: "6174", name: "Employer Social Security Contributions (CNSS)", type: "expense", subType: "operating" },
  { code: "6193", name: "Depreciation - Operating", type: "expense", subType: "operating" },
  { code: "6226", name: "Fees (Honoraires)", type: "expense", subType: "operating" },
  { code: "6311", name: "Interest on Loans", type: "expense", subType: "non_operating" },
  { code: "6331", name: "Foreign Exchange Losses", type: "expense", subType: "non_operating" },
  { code: "6701", name: "Corporate Income Tax (IS)", type: "expense", subType: "tax" },
  // Class 7: Produits (Revenue)
  { code: "7111", name: "Sales of Goods for Resale", type: "revenue", subType: "operating" },
  { code: "7121", name: "Sales of Finished Goods", type: "revenue", subType: "operating" },
  { code: "7124", name: "Sales of Services", type: "revenue", subType: "operating" },
  { code: "7127", name: "Ancillary Revenue", type: "revenue", subType: "operating" },
  { code: "7148", name: "Operating Grants", type: "revenue", subType: "non_operating" },
  { code: "7325", name: "Rental Income", type: "revenue", subType: "non_operating" },
  { code: "7331", name: "Foreign Exchange Gains", type: "revenue", subType: "non_operating" },
  { code: "7381", name: "Investment Income", type: "revenue", subType: "non_operating" },
  { code: "7513", name: "Gains on Disposal of Fixed Assets", type: "revenue", subType: "non_operating" },
];
